# Generated by Django 5.1.6 on 2025-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glucose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaded', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(max_length=40, verbose_name='User ID')),
                ('record_date', models.DateField(verbose_name='Date')),
                ('record_time', models.TimeField(verbose_name='Time')),
                ('glucose_value', models.IntegerField(verbose_name='Glucose Value mg/dL')),
            ],
            options={
                'ordering': ['-record_date', '-record_time'],
            },
        ),
    ]
