databases:
  - name: unahealthdb
    plan: free
    databaseName: unahealthdb
    user: unahealthdb_user

# Exported from Render on 2025-02-19T11:25:19Z
services:
- type: web
  name: unahealthAPI
  runtime: python
  repo: https://github.com/szew404/UnaHealthAPI
  plan: starter
  envVars:
  - key: CELERY_RESULT_BACKEND
    sync: false
  - key: DJANGO_ALLOWED_HOSTS
    sync: false
  - key: SQL_DATABASE
    sync: false
  - key: DATABASE
    sync: false
  - key: SQL_PORT
    sync: false
  - key: SQL_HOST
    sync: false
  - key: SQL_PASSWORD
    sync: false
  - key: SQL_USER
    sync: false
  - key: SQL_ENGINE
    sync: false
  - key: CELERY_BROKER_URL
    sync: false
  - key: DJANGO_SECRET_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./build.sh
  startCommand: python -m gunicorn src.config.asgi:application -k uvicorn.workers.UvicornWorker
version: "1"
